.TH "ax_abstract" 3 "Mar 9 2022" "axe"

.SH NAME
ax_begin_root_trait, ax_begin_trait, ax_begin_root_env, ax_begin_env, ax_abstract \- 一组定义类型构造函数的宏

.SH SYNOPSIS
.EX
#include <ax/class.h>

ax_begin_root_trait(name) ... ax_end

ax_begin_trait(name) ... ax_end

ax_begin_root_env(name) ... ax_end

ax_begin_env(name) ... ax_end

ax_abstract(n, name)

.EE

.SH DESCRIPTION

.SH SEE ALSO
\fBax_one\fP(3)

.SH AUTHOR
李希林 <lixilin@mail.ru>
